sir  = input('Intorduceti un sir: ')
print('Lungimea sirului este {}'.format(len(sir)))
print(f'Lungimea sirului este {len(sir)}')
print('Lungimea sirului este ' + str(len(sir)))
print('Lungimea sirului este',  len(sir))